# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value



services:
    blog.twig.extension.blog:
        class: BlogBundle\Twig\BlogExtension
        arguments: ["@doctrine"]
        tags:
            - { name: twig.extension }