services:
    user_mailer:
        class: UserBundle\Mailer\UserMailer
        arguments: ['@mailer', "marcingladkowski@gmail.com", "Marcin"]
    user_manager:
        class: UserBundle\Manager\UserManager
        arguments: ['@doctrine', '@router', '@templating', '@security.encoder_factory', '@user_mailer']
